### ISSUE TITLE
Get photo file location

### ISSUE THREAD

**Issue by pewh** [francisco-sanchez-molina/react-native-detect-new-photo#1]
Thanks for this repo. By the way, how can I can know where is the URL of detected new photo? Thanks

**Comment by francisco-sanchez-molina** [comment]
Currently this feature is not yet implemented, the solution is to call CameraRoll, and extract the new photo list. Sorry :/. 

(PR are welcome!)

**Comment by pewh** [comment]
Alright. I will close this issue. Hope somebody make PR because I didn't know either java or objective c :rofl:
